"""Render the fixture workspace's ``.winter/config.toml``.

Pure text generation: given the toy repos and their ``file://`` origins, produce
the minimal winter config that declares them as project repositories. The fixture
runs no winter *services* (the runner exercises the git/worktree binding, not the
service orchestrator), so the config carries only ``main_branch`` and the project
repos — every other field falls back to winter's own defaults.
"""

from __future__ import annotations

from collections.abc import Sequence


def render_config_toml(repos: Sequence[tuple[str, str]], *, main_branch: str = "main") -> str:
    """Render a minimal fixture ``.winter/config.toml``.

    ``repos`` is a sequence of ``(name, url)`` pairs; ``url`` is the ``file://``
    remote for the repo's bare origin. Names and URLs are toy-repo / path values
    with no TOML-special characters, so they are emitted verbatim.
    """
    lines = [
        "# Generated by blizzard-mock-fixture — a disposable fixture workspace.",
        "# The project repos below are bare file:// origins minted alongside this",
        "# workspace; the mock forge fronts the same origins (one git truth).",
        f'main_branch = "{main_branch}"',
        "",
    ]
    for name, url in repos:
        lines += [
            "[[project_repository]]",
            f'name = "{name}"',
            f'url = "{url}"',
            "",
        ]
    return "\n".join(lines)
