"""Render the fixture workspace's ``.winter/config.toml``.

Pure text generation: given toy repos and their ``file://`` origins, produce
the minimal winter config declaring them as project repositories; every other
field falls back to winter's own defaults.
"""

from __future__ import annotations

from collections.abc import Sequence


def render_config_toml(repos: Sequence[tuple[str, str]], *, main_branch: str = "main") -> str:
    """Render a minimal fixture ``.winter/config.toml``.

    ``repos`` is a sequence of ``(name, url)`` pairs; ``url`` is the ``file://``
    remote for the repo's bare origin, emitted verbatim.
    """
    lines = [
        "# Generated by blizzard-mock-fixture — a disposable fixture workspace.",
        "# The project repos below are bare file:// origins minted alongside this",
        "# workspace; the mock forge fronts the same origins (one git truth).",
        f'main_branch = "{main_branch}"',
        "",
    ]
    for name, url in repos:
        lines += [
            "[[project_repository]]",
            f'name = "{name}"',
            f'url = "{url}"',
            "",
        ]
    return "\n".join(lines)
