"""Bake a validated lever set into a standalone zipapp fake-OpenCode binary.

Runs inside blizzard-mock's own venv at ``mock-opencode emit`` time — never
inside the emitted artifact, which is why this is the one module in the
package allowed to import non-stdlib-adjacent stdlib tooling
(``zipapp``/``shutil``/``tempfile``) freely: it never gets copied into the
zip it builds.
"""

from __future__ import annotations

import shutil
import tempfile
import zipapp
from pathlib import Path

from .levers import Lever

_PACKAGE_ROOT = Path(__file__).resolve().parent

#: Everything zip-safe and stdlib-only — copied verbatim into the staged
#: artifact. ``emit.py`` itself is deliberately excluded.
_SOURCE_MEMBERS = ("__init__.py", "levers.py", "cli.py", "domain", "internal")


def emit(
    out: Path,
    *,
    levers: frozenset[Lever] = frozenset(),
    version: str = "1.18.25",
    auth_read_marker: str | None = None,
    version_touch_path: str | None = None,
) -> None:
    """Write an executable zipapp to ``out``, baked with the given lever set.

    ``out``'s parent must already exist — this never creates directories,
    only the one file the caller named.
    """
    with tempfile.TemporaryDirectory() as scratch_name:
        scratch = Path(scratch_name)
        staging = scratch / "opencode_surface"
        staging.mkdir()
        for name in _SOURCE_MEMBERS:
            source = _PACKAGE_ROOT / name
            destination = staging / name
            if source.is_dir():
                shutil.copytree(source, destination, ignore=shutil.ignore_patterns("__pycache__"))
            else:
                shutil.copy2(source, destination)
        (staging / "_baked.py").write_text(_render_baked(levers, version, auth_read_marker, version_touch_path))
        # Not zipapp's own `main=` convenience: its generated `__main__.py` just calls
        # `{module}.{fn}()` with no `sys.exit()`, so `cli.main()`'s return value — every
        # non-exception exit code `PERMISSION_NONZERO`/`FRESH_NONZERO` rely on — would be
        # silently discarded and the process would always exit 0.
        (scratch / "__main__.py").write_text("import sys\n\nimport opencode_surface.cli\n\nsys.exit(opencode_surface.cli.main())\n")
        zipapp.create_archive(scratch, target=out, interpreter="/usr/bin/env python3")
    out.chmod(0o755)


def _render_baked(
    levers: frozenset[Lever], version: str, auth_read_marker: str | None, version_touch_path: str | None
) -> str:
    """The generated ``_baked.py`` module text — the artifact's own fixed configuration."""
    names = ", ".join(f"Lever.{lever.name}" for lever in sorted(levers, key=lambda member: member.name))
    lever_expr = f"frozenset({{{names}}})" if names else "frozenset()"
    return (
        '"""Generated by emit.py — this artifact\'s fixed, immutable configuration."""\n'
        "from __future__ import annotations\n\n"
        "from .levers import Lever\n\n"
        f"LEVERS: frozenset[Lever] = {lever_expr}\n"
        f"VERSION: str = {version!r}\n"
        f"AUTH_READ_MARKER: str | None = {auth_read_marker!r}\n"
        f"VERSION_TOUCH_PATH: str | None = {version_touch_path!r}\n"
    )


__all__ = ["emit"]
