"""Bake a validated lever set into a standalone zipapp fake-OpenCode binary.

Runs inside blizzard-mock's own venv at ``mock-opencode emit`` time, never
inside the emitted artifact — the one module allowed to import
``zipapp``/``shutil``/``tempfile`` freely, since it never gets zipped in."""

from __future__ import annotations

import shutil
import tempfile
import zipapp
from pathlib import Path

from .levers import Lever

_PACKAGE_ROOT = Path(__file__).resolve().parent

#: Never copied into the artifact: this module, and ``_baked.py`` (regenerated fresh below).
_EXCLUDED_MEMBERS = {"emit.py", "_baked.py", "__pycache__"}


def _discover_source_members() -> tuple[str, ...]:
    """Every top-level package member the artifact ships — everything under
    ``opencode_surface/`` except the excluded ones, discovered rather than
    hand-listed so a module added later can't silently go missing from the zipapp."""
    return tuple(
        sorted(
            entry.name
            for entry in _PACKAGE_ROOT.iterdir()
            if entry.name not in _EXCLUDED_MEMBERS and (entry.is_dir() or entry.suffix == ".py")
        )
    )


def emit(
    out: Path,
    *,
    levers: frozenset[Lever] = frozenset(),
    version: str = "1.18.25",
    auth_read_marker: str | None = None,
    version_touch_path: str | None = None,
) -> None:
    """Write an executable zipapp to ``out``, baked with the given lever set.

    ``out``'s parent must already exist — this never creates directories,
    only the one file the caller named.
    """
    with tempfile.TemporaryDirectory() as scratch_name:
        scratch = Path(scratch_name)
        staging = scratch / "opencode_surface"
        staging.mkdir()
        for name in _discover_source_members():
            source = _PACKAGE_ROOT / name
            destination = staging / name
            if source.is_dir():
                shutil.copytree(source, destination, ignore=shutil.ignore_patterns("__pycache__"))
            else:
                shutil.copy2(source, destination)
        (staging / "_baked.py").write_text(_render_baked(levers, version, auth_read_marker, version_touch_path))
        # Not zipapp's own `main=`: its generated shim drops `cli.main()`'s return value,
        # silently discarding every nonzero exit code a lever like PERMISSION_NONZERO relies on.
        (scratch / "__main__.py").write_text(
            "import sys\n\nimport opencode_surface.cli\n\nsys.exit(opencode_surface.cli.main())\n"
        )
        zipapp.create_archive(scratch, target=out, interpreter="/usr/bin/env python3")
    out.chmod(0o755)


def _render_baked(
    levers: frozenset[Lever], version: str, auth_read_marker: str | None, version_touch_path: str | None
) -> str:
    """The generated ``_baked.py`` module text — the artifact's own fixed configuration."""
    names = ", ".join(f"Lever.{lever.name}" for lever in sorted(levers, key=lambda member: member.name))
    lever_expr = f"frozenset({{{names}}})" if names else "frozenset()"
    return (
        '"""Generated by emit.py — this artifact\'s fixed, immutable configuration."""\n'
        "from __future__ import annotations\n\n"
        "from .levers import Lever\n\n"
        f"LEVERS: frozenset[Lever] = {lever_expr}\n"
        f"VERSION: str = {version!r}\n"
        f"AUTH_READ_MARKER: str | None = {auth_read_marker!r}\n"
        f"VERSION_TOUCH_PATH: str | None = {version_touch_path!r}\n"
    )


__all__ = ["emit"]
